### ISSUE TITLE
liftext not working

### ISSUE THREAD

**Issue by ghost** [bug400/lifutils#2]
On linux `liftext FILE.LIF` command does not working for me. FILE.LIF is a real LIF file. No error message, the comand line just waiting for characters.

**Comment by bug400** [comment]
liftext is a filter. Use `liftext < FILE.LIF` to display the text on standard output or `liftext < FILE.LIF > result.txt` to store the output in file `result.txt`. See the online help: `man liftext`.

**Comment by ghost** [comment]
Thanks. Can you attach an example LIF file, because my LIF files have `HFSLIF` and `WS_FILE` tags inside and the liftext always gives back garbage and `***liftext: Unexpected end of file` error.

**Comment by bug400** [comment]
Sorry I was wrong with my last comment. `Liftext` expects a raw file not a LIF file. This is correct way using the sample file attached [test.zip](https://github.com/bug400/lifutils/files/2028126/test.zip):

`lifheader dir.lif` shows that this is a LIF file with a LIF header of type 1 (Text).

`cat dir.lif | lifraw | liftext` removes the LIF header (`lifraw`), converts the LIF1 text file to an ASCII file and sends it to standard output.

See the new [LIFUTILS tutorial ](https://rawgit.com/bug400/lifutils/master/doc/readme.html) for an introduction. Note: the documentation reflects version 1.7.8 of the LIFUTILS which has not been released up to now (see change log in the readme file). The scope of the LIFUTILS are files for the HP Calculators HP-41, HP-71B and HP-75.

**Comment by ghost** [comment]
Here is my file:
[CB01.TEXT.zip](https://github.com/bug400/lifutils/files/2028268/CB01.TEXT.zip)
My file looks different than your test example file. What do you think, what is the file format of this file and how to convert it to ASCII? I copied it from a HP-UX computer, that's why I thinked this is a LIF file.
There is `HFSLIF` in the header, what does it mean?

**Comment by bug400** [comment]
I found [this forum posts](https://community.hpe.com/t5/General/HFSLIF-Rocky-Mountain-Basic-file-conversion-to-readable-ASCII/td-p/3873829). Your `CB01.TEXT` file is actually a LIF image file (not a LIF file) labelled `HFSLIF`which contains a single file `WS_FILE` of LIF file type HP-UX basic.

Do a `lifdir CB01.TXT` to get a directory listing.

Extracting the file is a little bit tricky since the file name does not apply to the LIFUTILS file name scheme. So rename the file first:

`lifrename CB01.TEXT WS_FILE WSFILE`
`lifget CB01.TEXT WSFILE > ws_file.lif`
`lifheader ws_file.lif` shows that it is a file of type `ea3e` which is not known to the LIFUTILS because the focus is on HP-41, HP-71 and HP-75 files.

`cat ws_file.lif | lifraw > ws_file.raw` removes the LIF header and returns the "plain" HP-UX basic file. It contains binary data and ASCII text. You can extract the ASCII text with the Unix `strings` command. But I don't know if this is exactly the source code of the basic program.

**Comment by ghost** [comment]
Thanks, it works.
I suggest LIFUTILS to support to read `ea3e` file type to convert such a files to ASCII text file.
